Don't kill; instead use ifs.

diff --git a/faial-bench b/faial-bench
--- a/faial-bench
+++ b/faial-bench
@@ -17,31 +17,32 @@ cleanup(){
 
 trap "{ cleanup; }" EXIT
 
-do_abort() {
-  cleanup
-  kill 0
-}
-
-cu-to-json "$FILE" --extra-arg=-ferror-limit=1 > "${TMP1}" 2> "${TMP2}" || (
-  >&2 echo "cu-to-json $FILE"
+if ! cu-to-json "$FILE" --extra-arg=-ferror-limit=1 > "${TMP1}" 2> "${TMP2}"
+then
+  >&2 echo "ERROR: cu-to-json $FILE"
   echo "-------------------------------------------------------------------" >> "${PARSE_LOG}";
-  cat "ERROR: ${TMP2}" >> "$PARSE_LOG";
-  do_abort;
-)
+  cat "${TMP2}" >> "$PARSE_LOG"
+  cleanup
+  exit 1
+fi
 
-faial-infer "${TMP1}" -t json > "${TMP2}" 2> "${TMP3}" || (
-  >&2 echo "faial-infer $FILE"
+if ! faial-infer "${TMP1}" -t json > "${TMP2}" 2> "${TMP3}"; then
+  >&2 echo "ERROR: faial-infer $FILE"
   echo "-------------------------------------------------------------------" >> "${INFER_LOG}";
   echo "ERROR: $FILE" >> "${INFER_LOG}";
   cat "${TMP3}" >> "${INFER_LOG}";
-  do_abort;
-)
-main --json "${TMP2}" $(faial-gv "$FILE") > "${TMP1}" || (
-  >&2 echo "faial $FILE"
+  cleanup;
+  exit 2
+fi
+
+if ! main --json "${TMP2}" $(faial-gv "$FILE") > "${TMP1}"; then
+  >&2 echo "ERROR: faial $FILE"
   echo "-------------------------------------------------------------------" >> "${FAIAL_LOG}";
   echo "ERROR: $FILE" >> "${FAIAL_LOG}";
   cat "${TMP1}" >> "${FAIAL_LOG}";
-  do_abort
-)
+  cleanup
+  exit 3
+fi
+
 echo "${FILE}"
 cleanup
